COMMENT ON TABLE schema_migrations IS '数据库迁移记录表，用于记录每个 migration 文件是否已执行以及校验和';
COMMENT ON COLUMN schema_migrations.version IS '迁移版本号，例如 001、002';
COMMENT ON COLUMN schema_migrations.name IS '迁移文件名称';
COMMENT ON COLUMN schema_migrations.checksum IS '迁移文件内容 SHA256 校验和，用于防止已执行脚本被修改';
COMMENT ON COLUMN schema_migrations.applied_at IS '迁移应用时间';

COMMENT ON TABLE postcall_jobs IS '报警音频分析任务主表，每条记录代表一个接警单号对应的一次音频分析任务';
COMMENT ON COLUMN postcall_jobs.id IS '内部 UUID 主键';
COMMENT ON COLUMN postcall_jobs.job_id IS '对外返回的任务编号';
COMMENT ON COLUMN postcall_jobs.jjdh IS '接警单号，当前接口幂等键';
COMMENT ON COLUMN postcall_jobs.audio_url IS '首次提交的远程音频地址，重复提交时不覆盖';
COMMENT ON COLUMN postcall_jobs.bjsj IS '报警时间';
COMMENT ON COLUMN postcall_jobs.jcjxtjsdwmc IS '上游字段 JCJXTJSDWMC，接警系统推送单位名称';
COMMENT ON COLUMN postcall_jobs.jjdwmc IS '上游字段 JJDWMC，接警单位名称';
COMMENT ON COLUMN postcall_jobs.gxdwmc IS '上游字段 GXDWMC，管辖单位名称';
COMMENT ON COLUMN postcall_jobs.bjdh IS '报警电话';
COMMENT ON COLUMN postcall_jobs.bjrmc IS '报警人姓名';
COMMENT ON COLUMN postcall_jobs.bjrxbdm IS '报警人性别代码，只允许 0、1、2';
COMMENT ON COLUMN postcall_jobs.lxdh IS '联系电话';
COMMENT ON COLUMN postcall_jobs.jqdz IS '警情地址';
COMMENT ON COLUMN postcall_jobs.bjnr IS '报警内容，当前音频风险分析不使用该文本做判断，仅用于追溯';
COMMENT ON COLUMN postcall_jobs.jqlbdm IS '警情类别代码';
COMMENT ON COLUMN postcall_jobs.jqlxdm IS '警情类型代码';
COMMENT ON COLUMN postcall_jobs.jqxldm IS '警情细类代码，可为空';
COMMENT ON COLUMN postcall_jobs.jqzldm IS '警情子类代码，可为空';
COMMENT ON COLUMN postcall_jobs.jqdj IS '警情等级';
COMMENT ON COLUMN postcall_jobs.callback_url IS '上游回调地址，可为空';
COMMENT ON COLUMN postcall_jobs.asr_result IS '外部 ASR 分段结果，JSON 数组，当前不参与音频风险判断';
COMMENT ON COLUMN postcall_jobs.raw_payload IS 'API 原始请求体 JSON，用于审计和问题追溯';
COMMENT ON COLUMN postcall_jobs.client_id IS '通过 X-API-Key 鉴权得到的客户端 ID';
COMMENT ON COLUMN postcall_jobs.source_system IS '来源系统标识，来自客户端配置';
COMMENT ON COLUMN postcall_jobs.status IS '任务状态：queued、downloading、analyzing、completed、failed、cancelled';
COMMENT ON COLUMN postcall_jobs.priority IS '任务优先级，worker 拉取任务时可按该字段排序';
COMMENT ON COLUMN postcall_jobs.duplicate_count IS '同一接警单号重复提交次数';
COMMENT ON COLUMN postcall_jobs.locked_by IS '当前锁定该任务的 worker 标识';
COMMENT ON COLUMN postcall_jobs.locked_at IS 'worker 锁定任务时间';
COMMENT ON COLUMN postcall_jobs.locked_until IS 'worker 锁过期时间，用于异常退出后的任务恢复';
COMMENT ON COLUMN postcall_jobs.attempt_count IS '任务已尝试分析次数';
COMMENT ON COLUMN postcall_jobs.max_attempts IS '任务最大分析尝试次数';
COMMENT ON COLUMN postcall_jobs.next_run_at IS '任务下次允许执行时间，失败重试时可延后';
COMMENT ON COLUMN postcall_jobs.last_heartbeat_at IS 'worker 最近心跳时间，用于判断长任务是否仍在运行';
COMMENT ON COLUMN postcall_jobs.started_at IS '任务开始分析时间';
COMMENT ON COLUMN postcall_jobs.completed_at IS '任务分析完成时间';
COMMENT ON COLUMN postcall_jobs.failed_at IS '任务分析失败时间';
COMMENT ON COLUMN postcall_jobs.error_code IS '任务失败错误码';
COMMENT ON COLUMN postcall_jobs.error_message IS '任务失败错误信息';
COMMENT ON COLUMN postcall_jobs.created_at IS '记录创建时间';
COMMENT ON COLUMN postcall_jobs.updated_at IS '记录更新时间，由触发器自动刷新';

COMMENT ON TABLE postcall_job_duplicate_submissions IS '报警音频任务重复提交记录表，用于审计同一接警单号的重复请求';
COMMENT ON COLUMN postcall_job_duplicate_submissions.id IS '自增主键';
COMMENT ON COLUMN postcall_job_duplicate_submissions.postcall_job_id IS '关联的报警音频分析任务内部 ID';
COMMENT ON COLUMN postcall_job_duplicate_submissions.jjdh IS '重复提交的接警单号';
COMMENT ON COLUMN postcall_job_duplicate_submissions.submitted_audio_url IS '本次重复提交携带的音频地址';
COMMENT ON COLUMN postcall_job_duplicate_submissions.original_audio_url IS '首次任务保存的原始音频地址';
COMMENT ON COLUMN postcall_job_duplicate_submissions.raw_payload IS '本次重复提交的完整请求体 JSON';
COMMENT ON COLUMN postcall_job_duplicate_submissions.client_id IS '本次请求的客户端 ID';
COMMENT ON COLUMN postcall_job_duplicate_submissions.source_system IS '本次请求的来源系统标识';
COMMENT ON COLUMN postcall_job_duplicate_submissions.created_at IS '重复提交记录创建时间';

COMMENT ON TABLE postcall_audio_assets IS '报警音频文件资产表，用于记录原始音频、标准化音频、VAD 片段和证据片段';
COMMENT ON COLUMN postcall_audio_assets.id IS '内部 UUID 主键';
COMMENT ON COLUMN postcall_audio_assets.postcall_job_id IS '关联的报警音频分析任务内部 ID';
COMMENT ON COLUMN postcall_audio_assets.asset_type IS '音频资产类型：source、normalized、vad_segment、evidence_clip';
COMMENT ON COLUMN postcall_audio_assets.uri IS '音频文件位置，可为本地路径、对象存储地址或内部资源 URI';
COMMENT ON COLUMN postcall_audio_assets.content_type IS '音频文件 MIME 类型';
COMMENT ON COLUMN postcall_audio_assets.sha256 IS '音频文件 SHA256 摘要，用于完整性校验和去重';
COMMENT ON COLUMN postcall_audio_assets.sample_rate IS '音频采样率';
COMMENT ON COLUMN postcall_audio_assets.channels IS '音频声道数';
COMMENT ON COLUMN postcall_audio_assets.duration_sec IS '音频时长，单位秒';
COMMENT ON COLUMN postcall_audio_assets.size_bytes IS '音频文件大小，单位字节';
COMMENT ON COLUMN postcall_audio_assets.metadata IS '音频资产扩展元数据，例如转码参数、来源文件名、切片策略';
COMMENT ON COLUMN postcall_audio_assets.created_at IS '记录创建时间';

COMMENT ON TABLE postcall_model_runs IS '模型或处理步骤运行记录表，用于审计音频预处理、VAD、模型推理和风险融合过程';
COMMENT ON COLUMN postcall_model_runs.id IS '内部 UUID 主键';
COMMENT ON COLUMN postcall_model_runs.postcall_job_id IS '关联的报警音频分析任务内部 ID';
COMMENT ON COLUMN postcall_model_runs.model_name IS '模型或处理器名称';
COMMENT ON COLUMN postcall_model_runs.model_version IS '模型版本、checkpoint 名称或内部版本号';
COMMENT ON COLUMN postcall_model_runs.model_role IS '模型职责：audio_preprocess、vad、voice_state、sound_event、embedding、reranker、fusion';
COMMENT ON COLUMN postcall_model_runs.status IS '运行状态：queued、running、succeeded、failed、skipped';
COMMENT ON COLUMN postcall_model_runs.started_at IS '本次运行开始时间';
COMMENT ON COLUMN postcall_model_runs.completed_at IS '本次运行完成时间';
COMMENT ON COLUMN postcall_model_runs.duration_ms IS '本次运行耗时，单位毫秒';
COMMENT ON COLUMN postcall_model_runs.input_ref IS '输入引用 JSON，例如音频资产 ID、切片范围、采样率';
COMMENT ON COLUMN postcall_model_runs.metrics IS '运行指标 JSON，例如耗时、片段数、资源占用';
COMMENT ON COLUMN postcall_model_runs.output_summary IS '输出摘要 JSON，用于保存关键结果摘要';
COMMENT ON COLUMN postcall_model_runs.error_code IS '运行失败错误码';
COMMENT ON COLUMN postcall_model_runs.error_message IS '运行失败错误信息';
COMMENT ON COLUMN postcall_model_runs.created_at IS '记录创建时间';

COMMENT ON TABLE postcall_analysis_results IS '报警音频分析最终结果表，每个任务最多一条最终分析结论';
COMMENT ON COLUMN postcall_analysis_results.id IS '内部 UUID 主键';
COMMENT ON COLUMN postcall_analysis_results.postcall_job_id IS '关联的报警音频分析任务内部 ID';
COMMENT ON COLUMN postcall_analysis_results.risk_level IS '最终风险等级：unknown、none、low、medium、high、critical';
COMMENT ON COLUMN postcall_analysis_results.need_attention IS '是否需要人工重点关注';
COMMENT ON COLUMN postcall_analysis_results.confidence IS '最终结果置信度，范围 0 到 1';
COMMENT ON COLUMN postcall_analysis_results.risk_types IS '风险类型数组，例如尖叫、冲突、呼吸异常等归一化风险标签';
COMMENT ON COLUMN postcall_analysis_results.summary IS '面向业务人员展示的分析摘要';
COMMENT ON COLUMN postcall_analysis_results.recommended_actions IS '建议动作数组，例如升级复核、回听证据片段';
COMMENT ON COLUMN postcall_analysis_results.model_versions IS '本次分析使用的模型版本信息 JSON';
COMMENT ON COLUMN postcall_analysis_results.audio_processing IS '音频处理摘要 JSON，例如总时长、有效人声比例、切片数量';
COMMENT ON COLUMN postcall_analysis_results.fusion_trace IS '风险融合过程 JSON，用于解释最终结论来源';
COMMENT ON COLUMN postcall_analysis_results.result_payload IS '完整结果 JSON，用于对外返回或内部追溯';
COMMENT ON COLUMN postcall_analysis_results.created_at IS '记录创建时间';
COMMENT ON COLUMN postcall_analysis_results.updated_at IS '记录更新时间，由触发器自动刷新';

COMMENT ON TABLE postcall_timeline_events IS '报警音频时间线事件表，用于记录第几秒出现的人声状态、声音事件、风险推断和音频质量事件';
COMMENT ON COLUMN postcall_timeline_events.id IS '内部 UUID 主键';
COMMENT ON COLUMN postcall_timeline_events.postcall_job_id IS '关联的报警音频分析任务内部 ID';
COMMENT ON COLUMN postcall_timeline_events.analysis_result_id IS '关联的最终分析结果 ID，可为空';
COMMENT ON COLUMN postcall_timeline_events.start_sec IS '事件开始时间，单位秒';
COMMENT ON COLUMN postcall_timeline_events.end_sec IS '事件结束时间，单位秒';
COMMENT ON COLUMN postcall_timeline_events.event_type IS '事件类型：voice_state、sound_event、derived_risk、audio_quality、system';
COMMENT ON COLUMN postcall_timeline_events.label IS '归一化事件标签，用于程序判断';
COMMENT ON COLUMN postcall_timeline_events.label_zh IS '中文展示标签';
COMMENT ON COLUMN postcall_timeline_events.label_en IS '英文展示标签';
COMMENT ON COLUMN postcall_timeline_events.native_label IS '模型原生标签，例如 AudioSet 或 WavLM 原始标签';
COMMENT ON COLUMN postcall_timeline_events.score IS '模型分数或融合分数，范围 0 到 1';
COMMENT ON COLUMN postcall_timeline_events.severity IS '事件严重程度，例如 low、medium、high';
COMMENT ON COLUMN postcall_timeline_events.model_name IS '产生该事件的模型、处理器或规则名称';
COMMENT ON COLUMN postcall_timeline_events.model_version IS '产生该事件的模型版本或规则版本';
COMMENT ON COLUMN postcall_timeline_events.evidence IS '事件证据 JSON，例如 top labels、阈值、原始概率';
COMMENT ON COLUMN postcall_timeline_events.created_at IS '记录创建时间';

COMMENT ON TABLE postcall_evidence_segments IS '报警音频证据片段表，用于保存需要人工重点回听或支撑结论解释的关键音频片段';
COMMENT ON COLUMN postcall_evidence_segments.id IS '内部 UUID 主键';
COMMENT ON COLUMN postcall_evidence_segments.postcall_job_id IS '关联的报警音频分析任务内部 ID';
COMMENT ON COLUMN postcall_evidence_segments.analysis_result_id IS '关联的最终分析结果 ID，可为空';
COMMENT ON COLUMN postcall_evidence_segments.segment_id IS '片段编号，同一任务内唯一';
COMMENT ON COLUMN postcall_evidence_segments.start_sec IS '证据片段开始时间，单位秒';
COMMENT ON COLUMN postcall_evidence_segments.end_sec IS '证据片段结束时间，单位秒';
COMMENT ON COLUMN postcall_evidence_segments.risk_level IS '该证据片段对应的风险等级';
COMMENT ON COLUMN postcall_evidence_segments.reason IS '该片段被选为证据的原因';
COMMENT ON COLUMN postcall_evidence_segments.recommended_action IS '针对该证据片段的建议动作';
COMMENT ON COLUMN postcall_evidence_segments.clip_uri IS '证据音频片段文件地址，可为空';
COMMENT ON COLUMN postcall_evidence_segments.payload IS '证据片段详情 JSON，例如关联时间线事件、模型分数、阈值';
COMMENT ON COLUMN postcall_evidence_segments.created_at IS '记录创建时间';

COMMENT ON TABLE postcall_callback_deliveries IS '报警音频分析结果回调投递表，用于记录向上游系统回调的状态、重试和响应信息';
COMMENT ON COLUMN postcall_callback_deliveries.id IS '内部 UUID 主键';
COMMENT ON COLUMN postcall_callback_deliveries.postcall_job_id IS '关联的报警音频分析任务内部 ID';
COMMENT ON COLUMN postcall_callback_deliveries.delivery_type IS '回调类型：analysis_completed、analysis_failed';
COMMENT ON COLUMN postcall_callback_deliveries.callback_url IS '实际投递的上游回调地址';
COMMENT ON COLUMN postcall_callback_deliveries.status IS '投递状态：pending、running、succeeded、failed、abandoned';
COMMENT ON COLUMN postcall_callback_deliveries.attempt_count IS '已尝试投递次数';
COMMENT ON COLUMN postcall_callback_deliveries.max_attempts IS '最大投递尝试次数';
COMMENT ON COLUMN postcall_callback_deliveries.next_attempt_at IS '下次允许投递时间';
COMMENT ON COLUMN postcall_callback_deliveries.last_attempt_at IS '最近一次投递时间';
COMMENT ON COLUMN postcall_callback_deliveries.succeeded_at IS '投递成功时间';
COMMENT ON COLUMN postcall_callback_deliveries.request_payload IS '实际回调请求体 JSON';
COMMENT ON COLUMN postcall_callback_deliveries.response_status IS '上游响应 HTTP 状态码';
COMMENT ON COLUMN postcall_callback_deliveries.response_body IS '上游响应内容摘要';
COMMENT ON COLUMN postcall_callback_deliveries.error_code IS '投递失败错误码';
COMMENT ON COLUMN postcall_callback_deliveries.error_message IS '投递失败错误信息';
COMMENT ON COLUMN postcall_callback_deliveries.locked_by IS '当前锁定该回调任务的 worker 标识';
COMMENT ON COLUMN postcall_callback_deliveries.locked_at IS 'worker 锁定回调任务时间';
COMMENT ON COLUMN postcall_callback_deliveries.locked_until IS 'worker 锁过期时间，用于异常退出后的回调恢复';
COMMENT ON COLUMN postcall_callback_deliveries.created_at IS '记录创建时间';
COMMENT ON COLUMN postcall_callback_deliveries.updated_at IS '记录更新时间，由触发器自动刷新';
